### PR TITLE
Signed ECIES Payloads

### PR DESCRIPTION
**Pull request by neekolas**
## Summary

- Adds a new `SignedPayload` message type to hold arbitrary bytes and a signature
- Adds a wrapper type for `EciesMessage`, which currently just holds a `v1` structure for encrypted `SignedPayload` messages

### CODE REVIEW

**Review by nakajima — APPROVED** [review]

**Comment by richardhuaaa** [comment]
@neekolas this is for the v2 portable preferences right? Does this belong in `main`?

**Comment by neekolas** [comment]
You would think so, but libxmtp only looks at the v3 branch. Including in libxmtp's V2 branch. 

We could change that, since it's quite confusing.

**Comment by richardhuaaa** [comment]
Ahhh gotcha. Fine with leaving it as-is for now

**Comment by neekolas** [comment]
Really what I'd like to do is kill the v3 proto branch. None of our v3 work to date has involved changing any v2 protos, and I don't think it will. So the separate branching strategy isn't protecting us from much.

**Pull request merged**
